services:
  # MySQL or MariaDB
  dbs:
    build:
      context: ./img/${DB_ENGINE}
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    env_file: .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./dbs:/var/lib/mysql
    networks:
      - wpnet

  # PHPMyAdmin
  pma:
    build:
      context: ./img/phpmyadmin
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION}
    container_name: ${PMA_CONTAINER_NAME}
    env_file: .env
    depends_on:
      - dbs
    ports:
      - "${PMA_PORT}:8080"
    networks:
      - wpnet

  # WordPress
  web:
    build:
      context: ./img/wordpress
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION}
    container_name: ${WEB_CONTAINER_NAME}
    depends_on:
      - dbs
    env_file: .env
    volumes:
      - ./web:/var/www/html
    ports:
      - "${WP_PORT}:80"
    networks:
      - wpnet

  eml:
    build:
      context: ./img/mailhog
      args:
        - DEBIAN_VERSION=${DEBIAN_VERSION}
    container_name: ${MAILHOG_CONTAINER_NAME}
    ports:
      - "${MAILHOG_UI_PORT}:8025"
      - "${MAILHOG_SMTP_PORT}:1025"
    networks:
      - wpnet


networks:
  wpnet:
